/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as PressRouteImport } from './routes/press'
import { Route as OrderRouteImport } from './routes/order'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HoursRouteImport } from './routes/hours'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminHoursRouteImport } from './routes/admin.hours'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCateringRouteImport } from './routes/admin.catering'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursRoute = HoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCateringRoute = AdminCateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/catering': typeof CateringRoute
  '/gift-cards': typeof GiftCardsRoute
  '/hours': typeof HoursRoute
  '/locations': typeof LocationsRoute
  '/loyalty': typeof LoyaltyRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/press': typeof PressRoute
  '/reservations': typeof ReservationsRoute
  '/story': typeof StoryRoute
  '/admin/catering': typeof AdminCateringRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/catering': typeof CateringRoute
  '/gift-cards': typeof GiftCardsRoute
  '/hours': typeof HoursRoute
  '/locations': typeof LocationsRoute
  '/loyalty': typeof LoyaltyRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/press': typeof PressRoute
  '/reservations': typeof ReservationsRoute
  '/story': typeof StoryRoute
  '/admin/catering': typeof AdminCateringRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/catering': typeof CateringRoute
  '/gift-cards': typeof GiftCardsRoute
  '/hours': typeof HoursRoute
  '/locations': typeof LocationsRoute
  '/loyalty': typeof LoyaltyRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/press': typeof PressRoute
  '/reservations': typeof ReservationsRoute
  '/story': typeof StoryRoute
  '/admin/catering': typeof AdminCateringRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/catering'
    | '/gift-cards'
    | '/hours'
    | '/locations'
    | '/loyalty'
    | '/menu'
    | '/order'
    | '/press'
    | '/reservations'
    | '/story'
    | '/admin/catering'
    | '/admin/content'
    | '/admin/hours'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/catering'
    | '/gift-cards'
    | '/hours'
    | '/locations'
    | '/loyalty'
    | '/menu'
    | '/order'
    | '/press'
    | '/reservations'
    | '/story'
    | '/admin/catering'
    | '/admin/content'
    | '/admin/hours'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/catering'
    | '/gift-cards'
    | '/hours'
    | '/locations'
    | '/loyalty'
    | '/menu'
    | '/order'
    | '/press'
    | '/reservations'
    | '/story'
    | '/admin/catering'
    | '/admin/content'
    | '/admin/hours'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  CateringRoute: typeof CateringRoute
  GiftCardsRoute: typeof GiftCardsRoute
  HoursRoute: typeof HoursRoute
  LocationsRoute: typeof LocationsRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MenuRoute: typeof MenuRoute
  OrderRoute: typeof OrderRoute
  PressRoute: typeof PressRoute
  ReservationsRoute: typeof ReservationsRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours': {
      id: '/hours'
      path: '/hours'
      fullPath: '/hours'
      preLoaderRoute: typeof HoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hours': {
      id: '/admin/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catering': {
      id: '/admin/catering'
      path: '/catering'
      fullPath: '/admin/catering'
      preLoaderRoute: typeof AdminCateringRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCateringRoute: typeof AdminCateringRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminHoursRoute: typeof AdminHoursRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCateringRoute: AdminCateringRoute,
  AdminContentRoute: AdminContentRoute,
  AdminHoursRoute: AdminHoursRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  CateringRoute: CateringRoute,
  GiftCardsRoute: GiftCardsRoute,
  HoursRoute: HoursRoute,
  LocationsRoute: LocationsRoute,
  LoyaltyRoute: LoyaltyRoute,
  MenuRoute: MenuRoute,
  OrderRoute: OrderRoute,
  PressRoute: PressRoute,
  ReservationsRoute: ReservationsRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
